### ISSUE TITLE
missing Setup.hs

### ISSUE THREAD

**Issue by robx** [phadej/time-compat#4]
Not sure to what extent it's a valid choice to leave Setup.hs out -- feel free to close if so. 

Anyhow, I ran into trouble building this via guix (as a dependency to quickcheck-instances), which likes to use `runhaskell Setup.hs` for haskell builds.

**Comment by phadej** [comment]
I think it's a bug in `guix` tooling. E.g. https://github.com/haskell/cabal/issues/2629 is from 2015, and I have uploaded some packages used by others (including `nixpkgs` iirc) without `Setup.hs

**Comment by robx** [comment]
I'm inclined to agree by now; I also see how some packages work aroud this. Sorry for bugging you with this, and thanks for the quick reply!
